<?php

namespace OCP\AppliBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * analyseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class analyseRepository extends EntityRepository
{
}
