<?php

namespace OCP\AppliBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ParcRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParcRepository extends EntityRepository
{
    public function recherche($chaine)
{
            $qb = $this->createQueryBuilder('a');
                    $qb->where('a.nom = :nom')
                    ->setParameter('nom', $chaine)

                    ->orderBy('a.id', 'DESC');
      return $qb->getQuery()->getResult();
}
}
