<?php

namespace OCP\AppliBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ParcRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class recuRepository extends EntityRepository
{
    public function recherche($date)
{
            $qb = $this->createQueryBuilder('a');
                    $qb->where('a.date = :date')
                    ->setParameter('date', $date)

                    ->orderBy('a.date', 'DESC');
      return $qb->getQuery()->getResult();
}
}
