<?php

namespace OCP\AppliBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * trainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class trainRepository extends EntityRepository
{
    
    
    public function getTrain($id) {
        $qb = $this->createQueryBuilder('a');

        $qb->where('a.numero > :id')
          ->setParameter('id', $id);

        return $qb;
    }
}
